// Global Matrix Translation Registry Database
const GlobalLanguageDatabase = [
    { name: "English", code: "en" },
    { name: "Español (Spanish)", code: "es" },
    { name: "中文 (Chinese)", code: "zh" },
    { name: "हिन्दी (Hindi)", code: "hi" },
    { name: "العربية (Arabic)", code: "ar" },
    { name: "Français (French)", code: "fr" },
    { name: "Deutsch (German)", code: "de" },
    { name: "Русский (Russian)", code: "ru" },
    { name: "Português (Portuguese)", code: "pt" },
    { name: "日本語 (Japanese)", code: "ja" },
    { name: "Italiano (Italian)", code: "it" },
    { name: "한국어 (Korean)", code: "ko" },
    { name: "Türkçe (Turkish)", code: "tr" },
    { name: "Tiếng Việt (Vietnamese)", code: "vi" },
    { name: "Polski (Polish)", code: "pl" },
    { name: "Nederlands (Dutch)", code: "nl" },
    { name: "Українська (Ukrainian)", code: "uk" },
    { name: "Bahasa Indonesia (Indonesian)", code: "id" },
    { name: "ไทย (Thai)", code: "th" },
    { name: "فارسی (Persian)", code: "fa" },
    { name: "Svenska (Swedish)", code: "sv" },
    { name: "עברית (Hebrew)", code: "he" },
    { name: "Ελληνικά (Greek)", code: "el" },
    { name: "Čeština (Czech)", code: "cs" },
    { name: "Română (Romanian)", code: "ro" },
    { name: "Magyar (Hungarian)", code: "hu" },
    { name: "Dansk (Danish)", code: "da" },
    { name: "Suomi (Finnish)", code: "fi" },
    { name: "Norsk (Norwegian)", code: "no" },
    { name: "Slovenčina (Slovak)", code: "sk" },
    { name: "Català (Catalan)", code: "ca" },
    { name: "Filipino (Tagalog)", code: "tl" },
    { name: "বাংলা (Bengali)", code: "bn" },
    { name: "ਪੰਜਾਬੀ (Punjabi)", code: "pa" },
    { name: "ગુજરાਤੀ (Gujarati)", code: "gu" },
    { name: "தமிழ் (Tamil)", code: "ta" },
    { name: "తెలుగు (Telugu)", code: "te" },
    { name: "ಕನ್ನಡ (Kannada)", code: "kn" },
    { name: "മലയാളം (Malayalam)", code: "ml" },
    { name: "मराठी (Marathi)", code: "mr" },
    { name: "اردو (Urdu)", code: "ur" },
    { name: "Kiswahili (Swahili)", code: "sw" }
];
